# +--------------------------------------------------------------------------------------------------------------+
# |    ____     ___    _____   _       _     _      ____    _____   _   _   _    ___    ____    ____    _____    |
# |   |  _ \   / _ \  |_   _| | |     | |   | |    |  _ \  |  ___| | | | | | |  / _ \  |  _ \  |  _ \  /  ___\   |
# |   | | \ | | |_| |   | |   | |      \ \ / /     | |_| | | |___  | | | | | | | |_| | | |_| | | | \ | | |___    |
# |   | | | | |  _  |   | |   | |       \   /      |    /  |  ___| | | | | | | |  _  | |    /  | | | | |___  |   |
# |   | |_/ | | | | |  _| |_  | |___     | |       | |\ \  | |___  | |_| |_| | | | | | | |\ \  | |_/ |  ___| |   |
# |   |____/  |_| |_| |_____| |_____|    |_|       |_| \_\ |_____|  \_______/  |_| |_| |_| \_\ |____/  \_____/   |
# |                                                                                                              |
# +--------------------------------------------------------------------------------------------------------------+
#
# This config file will be generated by ${project.name} version ${project.version}.
# If this version older than current ${project.name} plugin version, you should regenerate this config.
# You just need rename (to save, but you can delete it) this file and use plugin reload command.
#
# Author and developer: SoKnight
# Developed for PlasticCraft project
#
# Configuration of database
database:
  # Should plugin use MySQL database as data storage?
  # Specify 'true' to use SQLite or 'false' to use MySQL
  use-sqlite: true

  # MySQL configuration
  host: localhost
  port: 3306
  name: dailyrewards
  user: admin
  password: dailyrewards
  
  # SQLite configuration
  file: database.db

# Daily rewards configuration
rewards: 
  # Operating currency from PEconomy config
  currency: 'dollars'

  # Start reward (on first day)
  start: 50

  # Coefficient of reward for next days
  # The formule is: s + s * (k * d * (1 + g))
  # s - start reward
  # d - day in queue
  # k - day coefficient (see miltiplier)
  # g - group coefficient (see group-bonuses)
  multiplier: 0.1

  # Days queue length
  # Count of days which after queue will reset
  max-queue-length: 10

# Group bonuses configuration
# [!] Only for LuckPerms (group.%name%)
# GROUP: BONUS (%) etc. 100% + BONUS% (0.2 is 20%)
group-bonuses:
  economist: 0.2
  businessman: 0.4
  millionaire: 0.6
  billionaire: 0.8
  president: 1