# +--------------------------------------------------------------------------------------------------------------+
# |    ____     ___    _____   _       _     _      ____    _____   _   _   _    ___    ____    ____    _____    |
# |   |  _ \   / _ \  |_   _| | |     | |   | |    |  _ \  |  ___| | | | | | |  / _ \  |  _ \  |  _ \  /  ___\   |
# |   | | \ | | |_| |   | |   | |      \ \ / /     | |_| | | |___  | | | | | | | |_| | | |_| | | | \ | | |___    |
# |   | | | | |  _  |   | |   | |       \   /      |    /  |  ___| | | | | | | |  _  | |    /  | | | | |___  |   |
# |   | |_/ | | | | |  _| |_  | |___     | |       | |\ \  | |___  | |_| |_| | | | | | | |\ \  | |_/ |  ___| |   |
# |   |____/  |_| |_| |_____| |_____|    |_|       |_| \_\ |_____|  \_______/  |_| |_| |_| \_\ |____/  \_____/   |
# |                                                                                                              |
# |   Автор: SoKnight                                                                            Версия: 1.0.0   |
# +--------------------------------------------------------------------------------------------------------------+
#
# Конфигурация базы данных
database:
  # Типы базы данных: [mysql, sqlite]
  type: sqlite
  # Конфигурация БД MySQL
  host: localhost
  port: 3306
  name: dailyrewards
  user: admin
  password: dailyrewards
  # Конфигурация БД SQLite
  file: dailyrewards.db
# Настройка ежедневных наград
rewards: 
  # Начальная награда (на первом дне)
  # Присутствует поддержка обоих валют (dollars и euro)
  start: 
    dollars: 50
  # Коэффицент награды за последующие дни
  # Формула расчёта: s + s * (k * d * (1 + g))
  # s - начальная награда
  # d - день в очереди
  # k - коэффицент дня (см. miltiplier)
  # g - коэффицент группы (см. group-bonuses)
  multiplier: 0.1
  # Максимальная длина очереди дней
  # Кол-во дней, после которого очередь сбросится
  max-queue-length: 10
# Настройка бонусов для групп
# [!] Используется LuckPerms (group.%name%)
# ГРУППА: БОНУС (%)
group-bonuses:
  economist: 0.2
  businessman: 0.4
  millionaire: 0.6
  billionaire: 0.8
  president: 1
# Сообщение о награде
# Возможные замены: %dollars%, %euro%, %day%
reward-message:
- ' '
- '    &eНАГРАДА ЗА ЕЖЕДНЕВНЫЙ ВХОД'
- '  &b%dollars%$ &fдобавлено к вашему балансу.'
- '  &fИ это ваш &b%day% &fдень.'
- '  &fЗаходите каждый день, чтобы получать больше.'
- ' '
# Сообщение о том, что награда уже получена
already-received:
  # Показывать ли данное сообщение
  enabled: true
  # Выводимое сообщение
  message: '&l[REWARDS] &fВы уже получили награду за сегодняшний день. Ждём вас завтра!'
# Сообщение о пропущенном дне
skipped-day:
  # Показывать ли данное сообщение
  enabled: true
  # Выводимое сообщение
  message: '&l[REWARDS] &fВы пропустили один или несколько дней и прервали очередь наград :('